"""
Coder Buddy - Shared State
============================
Defines the TypedDict state schema used by LangGraph
to pass data between agents in the pipeline.
"""

from __future__ import annotations
from typing import TypedDict, Optional


class CoderBuddyState(TypedDict):
    """
    The shared state object that flows through the multi-agent graph.

    Attributes
    ----------
    user_request : str
        The original natural-language request from the user.
    project_plan : str
        Output from the Planner Agent — the high-level project plan.
    architecture_tasks : str
        Output from the Architect Agent — detailed engineering tasks.
    generated_files : dict[str, str]
        Output from the Coder Agent — mapping of file paths -> code content.
    review_report : str
        Output from the Reviewer Agent — code-review feedback.
    needs_revision : bool
        Flag set by the Reviewer if the code needs to go back to the Coder.
    revision_count : int
        Tracks how many revision cycles have occurred (to avoid infinite loops).
    final_output : str
        The final consolidated output to display to the user.
    error : Optional[str]
        Any error message that occurred during processing.

    # ── RAG Codebase Context (Feature 1) ────────────────────────
    codebase_context : str
        Relevant code snippets retrieved from the user's existing project
        via RAG semantic search. Fed to the Architect for context.

    # ── Design-to-Code Vision (Feature 2) ───────────────────────
    design_description : str
        Text description of an uploaded wireframe/sketch image,
        generated by a vision model. Fed to the Planner.

    # ── Self-Healing Sandbox (Feature 3) ────────────────────────
    execution_result : str
        Output from running the generated code in a sandbox.
        Includes stdout, stderr, and any error tracebacks.
    sandbox_attempts : int
        Number of sandbox fix attempts (capped to prevent infinite loops).

    # ── Git Integration (Feature 4) ─────────────────────────────
    git_log : str
        Git commit log after auto-committing generated files.
    """
    user_request: str
    project_plan: str
    architecture_tasks: str
    generated_files: dict[str, str]
    review_report: str
    needs_revision: bool
    revision_count: int
    final_output: str
    error: Optional[str]

    # Feature 1: RAG
    codebase_context: str

    # Feature 2: Vision
    design_description: str

    # Feature 3: Sandbox
    execution_result: str
    sandbox_attempts: int

    # Feature 4: Git
    git_log: str
