"""
Coder Buddy - Reviewer Agent (QA)
====================================
The fourth agent in the pipeline. Reviews the Coder's output for
quality, correctness, and security — can send code back for revision.
"""

import json
from langchain_core.prompts import ChatPromptTemplate
from config import get_llm, wait_for_rate_limit


REVIEWER_SYSTEM_PROMPT = """You are the Senior Code Reviewer & QA Engineer for 'Coder Buddy', an elite AI development team.

Your job is to analyze code generated by the Coder Agent and provide thorough, actionable feedback.

You MUST evaluate the code across these dimensions:

### 1. Correctness
- Does the code implement the requirements from the architecture tasks?
- Are there logic errors or bugs?
- Do all functions handle edge cases?

### 2. Code Quality
- Is the code clean, readable, and well-organized?
- Are there proper docstrings and comments?
- Does the code follow language conventions (PEP 8 for Python, etc.)?
- Are type hints used consistently?

### 3. Error Handling
- Are exceptions properly caught and handled?
- Are there meaningful error messages?
- Does the code fail gracefully?

### 4. Security
- Are there any security vulnerabilities (SQL injection, XSS, hardcoded secrets, etc.)?
- Is user input properly validated and sanitized?

### 5. Completeness
- Are all required files present?
- Are any functions left unimplemented?
- Are there placeholder/TODO comments that should be actual code?

### 6. Integration
- Do all the files work together correctly?
- Are imports consistent and correct?
- Is the data flow between components sound?

OUTPUT FORMAT:
You MUST output your review in the following structure:

## Review Summary
**Overall Verdict**: PASS ✅ or NEEDS_REVISION ⚠️
**Quality Score**: X/10

## Issues Found
For each issue:
- **Severity**: 🔴 Critical / 🟡 Warning / 🟢 Suggestion
- **File**: `file_path`
- **Issue**: Description of the problem.
- **Fix**: How to fix it.

## Positive Aspects
List things the code does well.

## Final Recommendation
Brief summary of whether the code is ready for delivery or needs revision.

RULES:
- Be thorough but fair.
- Only mark as NEEDS_REVISION if there are 🔴 Critical issues.
- 🟡 Warnings and 🟢 Suggestions should NOT block approval unless there are many.
- If the code is functional and meets requirements, mark it PASS ✅ even with minor suggestions.
"""

REVIEWER_USER_PROMPT = """Here is the original user request:
---
{user_request}
---

Here are the architecture tasks the code should implement:
---
{architecture_tasks}
---

Here is the generated code to review:
---
{generated_files_str}
---

This is revision #{revision_count}.

Perform a thorough code review following the required structure."""


def create_reviewer_chain():
    """Creates and returns the Reviewer Agent's LLM chain."""
    llm = get_llm()
    prompt = ChatPromptTemplate.from_messages([
        ("system", REVIEWER_SYSTEM_PROMPT),
        ("human", REVIEWER_USER_PROMPT),
    ])
    return prompt | llm


def run_reviewer(state: dict) -> dict:
    """
    LangGraph node function for the Reviewer Agent.

    Reviews the generated code and determines if it needs revision.
    Sets `needs_revision` flag and `review_report`.
    """
    # Preserve any existing error from earlier agents (Planner/Architect/Coder)
    existing_error = state.get("error")

    # Skip review if there are no files to review
    files = state.get("generated_files", {})
    if not files:
        return {
            "review_report": (
                "## Review Skipped ⚠️\n\n"
                "**Reason**: No code files were generated to review.\n\n"
                "This usually means an earlier agent (Planner, Architect, or Coder) "
                "failed — check the error message above.\n\n"
                "**💡 Recommendations:**\n"
                "- Switch to **Groq Cloud** (free, fast, generous limits) — "
                "[Get free key →](https://console.groq.com/keys)\n"
                "- Or wait a few minutes and try again\n"
            ),
            "needs_revision": False,
            "revision_count": state.get("revision_count", 0),
            "error": existing_error,  # Preserve the real error from earlier agent
        }

    try:
        wait_for_rate_limit()
        chain = create_reviewer_chain()

        # Serialize generated files for the reviewer
        files_str = ""
        for path, content in files.items():
            files_str += f"\n{'='*60}\n📄 FILE: {path}\n{'='*60}\n{content}\n"

        revision_count = state.get("revision_count", 0)

        response = chain.invoke({
            "user_request": state["user_request"],
            "architecture_tasks": state["architecture_tasks"],
            "generated_files_str": files_str,
            "revision_count": str(revision_count),
        })

        review_content = response.content

        # Determine if revision is needed based on the verdict
        needs_revision = "NEEDS_REVISION" in review_content.upper()

        # Cap revision cycles to prevent infinite loops
        max_revisions = 2
        if revision_count >= max_revisions:
            needs_revision = False
            review_content += (
                f"\n\n⏹️ **Max revision limit reached ({max_revisions}).** "
                "Delivering current code as-is."
            )

        return {
            "review_report": review_content,
            "needs_revision": needs_revision,
            "revision_count": revision_count + 1,
            "error": existing_error,  # Preserve any earlier error
        }
    except Exception as e:
        error_msg = str(e)

        # Check if it's a rate-limit / quota error
        is_rate_limit = any(
            keyword in error_msg.upper()
            for keyword in ["429", "RESOURCE_EXHAUSTED", "RATE_LIMIT", "QUOTA"]
        )

        if is_rate_limit:
            # Gracefully skip review — deliver code as-is
            return {
                "review_report": (
                    "## Review Skipped ⚠️\n\n"
                    "**Reason**: API rate limit / quota exceeded.\n\n"
                    "The generated code has been delivered without automated review.\n\n"
                    "**💡 Recommendations:**\n"
                    "- Switch to **Groq Cloud** (free, fast, generous limits) — "
                    "[Get free key →](https://console.groq.com/keys)\n"
                    "- Or wait a few minutes and use the **Revise & Regenerate** "
                    "button to re-run the review\n"
                    "- You can also manually review the code in the **Code & Files** tab\n"
                ),
                "needs_revision": False,
                "revision_count": state.get("revision_count", 0) + 1,
                "error": existing_error,  # Preserve any earlier error
            }
        else:
            # Genuine error — report it but still deliver code
            return {
                "review_report": f"Reviewer encountered an error: {error_msg}",
                "needs_revision": False,
                "revision_count": state.get("revision_count", 0) + 1,
                "error": existing_error,  # Preserve any earlier error
            }


